name: Deploy demo
on: push
env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy demo to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: demo